version: "3"

services:
    traefik:
        image: traefik:latest
        restart: always
        networks:
            - web
        ports:
            - "80:80"
            - "443:443"
        volumes:
            - /var/run/docker.sock:/var/run/docker.sock
            - ${PWD}/traefik.toml:/traefik.toml
            - ${PWD}/traefik_dynamic.toml:/traefik_dynamic.toml
            - ${PWD}/acme.json:/acme.json

networks:
  web:
    external: true
