[http.middlewares.simpleAuth.basicAuth]
  users = [
    "admin:your-password-generated-with-htpasswd"
  ]

[http.routers.api]
  rule = "Host(`traefik.your-domain.com`)"
  entrypoints = ["websecure"]
  middlewares = ["simpleAuth"]
  service = "api@internal"
  [http.routers.api.tls]
    certResolver = "lets-encrypt"
