version: '3'

networks:
    web:
        external: true
    internal:
        external: false

services:
  nextcloud:
    image: nextcloud:latest
    restart: always
    depends_on:
      - nextcloud_db
    hostname: 'cloud.yourdomain.com'
    volumes:
      - ${PWD}/data/nextcloud:/var/www/html
    networks:
      - web
      - internal
    environment:
      - MYSQL_PASSWORD=nextcloud
      - MYSQL_DATABASE=nextcloud
      - MYSQL_USER=nextcloud
      - MYSQL_HOST=nextcloud_db
    expose:
    - "80"
    labels:
      - traefik.http.routers.nextcloud.rule=Host(`cloud.yourdomain.com`)
      - traefik.http.routers.nextcloud.tls=true
      - traefik.http.routers.nextcloud.tls.certresolver=lets-encrypt
      - traefik.http.services.nextcloud.loadbalancer.server.port=80
      - traefik.port=80
      
  nextcloud_db:
    image: mariadb:latest
    restart: always
    command: --transaction-isolation=READ-COMMITTED --binlog-format=ROW
    volumes:
      - ${PWD}/data/db:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=mypass
      - MYSQL_PASSWORD=nextcloud
      - MYSQL_DATABASE=nextcloud
      - MYSQL_USER=nextcloud
    networks:
      - internal
